language: python
python:
- '3.4'
sudo: false
install:
- pip install -e git+https://github.com/deconst/preparer-sphinx.git#egg=deconstrst
script:
- script/cibuild
env:
  global:
  - secure: ZH71GgFpOzvDxQPcHrV+EAek0Klzff8SjpdP5sCfD6zh8XURZORoPw9GubCivbYL09Js/LeH7nj9+x6f/uSj1uKVr5rG5JtRoI0Lja7D5MhbE4wjMcwEVBC2+S6BWr0Z+5tEnFJtGVqrEjhxatNOlUH5pSnAYmY23fys1Fu7MXM=
  - secure: B1cTzzMlmUfPip0+g+lLANsVGhYQb2U2vIp4Szn/NbsY9+YywDAhzTIbpUPNNcE55t0bjTR2PD8QTH2gJ4QubiaUdmxKnL0NHAxyLEgNqv43oyUdN2CXdi9jytHuo+k0zCdbKU8JukjgYP5wzSplrvAycA+6fmAIb4s43S9bDZY=
  - secure: G/tCGBEkK8yLWY41BA/xZEVkkZj8n9oqVfHnLSGSe3I99ueYUDmSkhBt9muOnOVQ8nU9mYihZm5qCsBepsxTZ9k1QXQRS9Qj2P7OLDspsQI/hKNjdMLBozPXxGRr/NQ648YxezQiIYBMuzZNmBVviJSArdEYcr0oNGMrzyYL56s=
notifications:
  slack:
    secure: hhwQpZQAHrR8HwJ0aUit/qUdzuCK8GGdwWSrnEGFII8PHQdEm9k0PF7bgLHqwNyQja5TcW2zVF9Xxj+E2b/CwxAJOqUvqsl6wo/BfeaVxPR2MlWMRHX3AQqI6qp+HZTHsJNDBXFnt8p/kKmiTs/ofao1uSWU+4x5UUzBmbWNl8I=
